ARG BASE_IMG

FROM ${BASE_IMG}

RUN conda install -n base -y \
    jupyterlab \
    ipywidgets && \
    conda clean --all --yes

ENV PATH=${PATH}:/opt/conda/bin

RUN mkdir -p /tmp/notebooks && chmod -R a+rwx /tmp/notebooks
ENTRYPOINT ["sh", "-c", "jupyter lab --notebook-dir=/tmp/notebooks --no-browser --ip=0.0.0.0 --allow-root --port=8888 --NotebookApp.token='' --NotebookApp.allow_origin='*'"]

