name: quay
    
on:
  workflow_dispatch:
    inputs:
      QISKIT_VERSION:
        description: 'The version used with qiskit'
        required: true
  push:
    tags:
      - "*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfiles
          tags: quay.io/mgiessing/qiskit:${{ github.event.inputs.QISKIT_VERSION || github.ref_name }}
          platforms: linux/amd64,linux/ppc64le,linux/s390x,linux/arm64
          push: true
          build-args: |
            QISKIT_VERSION=${{ github.event.inputs.QISKIT_VERSION || github.ref_name }}
        
      - name: Build and Push Image armv7l
        uses: docker/build-push-action@v3
        with:
          context: ./dockerfiles
          file: ./dockerfiles/Dockerfile.armv7l
          tags: quay.io/mgiessing/qiskit:${{ github.event.inputs.QISKIT_VERSION || github.ref_name }}-armv7l
          platforms: linux/arm/v7
          push: true
          build-args: |
            QISKIT_VERSION=${{ github.event.inputs.QISKIT_VERSION || github.ref_name }}
